version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=gtw
      - POSTGRES_PASSWORD=gtw
      - POSTGRES_DB=gtw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gtw"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://gtw:gtw@postgres:5432/gtw
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./src:/app/src:ro
      - ./dist:/app/dist

volumes:
  pgdata:
