version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - OLLAMA_BASE_URL=http://ollama:11434
      - DATABASE_URL=postgres://gtw:gtw@postgres:5432/gtw
      - DEMO_START=1
      - PORT=4000
    command: ["node", "--experimental-specifier-resolution=node", "dist/src/demo/sprint4-demo.js"]
    depends_on:
      - qdrant
      - nats
      - postgres
    restart: unless-stopped

  narrative:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/dist/src
    command: ["node", "--experimental-specifier-resolution=node", "demo/index.js"]
    environment:
      - NODE_ENV=production
      - OLLAMA_BASE_URL=http://ollama:11434
      - DATABASE_URL=postgres://gtw:gtw@postgres:5432/gtw
      - DEMO_START=1
    depends_on:
      - ollama
      - nats
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    # no host port mapping to avoid conflicts in local dev; reachable via service name within the network
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant:/qdrant/storage
    restart: unless-stopped

  nats:
    image: nats:2
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=gtw
      - POSTGRES_PASSWORD=gtw
      - POSTGRES_DB=gtw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  ollama:
  qdrant:
  pgdata:


