version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - nats
      - qdrant
    command: ["node", "--experimental-specifier-resolution=node", "dist/server/index.js"]
  nats:
    image: nats:2
  qdrant:
    image: qdrant/qdrant:latest


