apiVersion: v1
kind: Namespace
metadata:
  name: startales
  labels:
    name: startales
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: startales-quota
  namespace: startales
spec:
  hard:
    requests.cpu: "50"
    requests.memory: 100Gi
    limits.cpu: "100"
    limits.memory: 200Gi
    persistentvolumeclaims: "20"
    services: "50"
    secrets: "20"
    configmaps: "20"
