apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts
  namespace: startales
  labels:
    app: tts
    component: ai-service
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: tts
  template:
    metadata:
      labels:
        app: tts
        component: ai-service
    spec:
      containers:
      - name: tts
        image: startales/tts:latest
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: startales-config
        resources:
          requests:
            cpu: 1000m
            memory: 3Gi
          limits:
            cpu: 2000m
            memory: 6Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 2
        volumeMounts:
        - name: tts-models
          mountPath: /app/models
        - name: tts-cache
          mountPath: /app/cache
      volumes:
      - name: tts-models
        persistentVolumeClaim:
          claimName: tts-models-pvc
      - name: tts-cache
        persistentVolumeClaim:
          claimName: tts-cache-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tts
  namespace: startales
  labels:
    app: tts
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: tts
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tts-models-pvc
  namespace: startales
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tts-cache-pvc
  namespace: startales
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tts-hpa
  namespace: startales
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tts
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
