services:
  ui:
    build:
      context: ..
      dockerfile: docker/services/ui/Dockerfile.ui
    ports:
      - "5173:5173"
    volumes:
      - ../src:/app/src
      - ../vite.config.ts:/app/vite.config.ts
      - ../tsconfig.docker.json:/app/tsconfig.json
      - ../package.json:/app/package.json
      - ../package-lock.json:/app/package-lock.json
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api:
    build:
      context: ..
      dockerfile: docker/services/api/Dockerfile.demo
    ports:
      - "4000:4000"
      - "4010:4010"
    environment:
      - NODE_ENV=production
      - PORT=4010
    # Run the main demo server with all systems including Population Engine
    command: ["npx", "tsx", "src/demo/index.ts"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4010/api/population/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    name: startales_demo
