version: '3.8'

# Master orchestration file for all Startales microservices
# Use this to start the complete system or individual service groups

services:
  # Core application services (lightweight)
  api:
    extends:
      file: services/api/docker-compose.api.yml
      service: api
    depends_on:
      - postgres
      - redis
      - nats

  ui:
    extends:
      file: services/ui/docker-compose.ui.yml
      service: ui
    depends_on:
      - api

  # Database services (moderate resource usage)
  postgres:
    extends:
      file: services/database/docker-compose.db.yml
      service: postgres

  redis:
    extends:
      file: services/database/docker-compose.db.yml
      service: redis

  nats:
    extends:
      file: services/database/docker-compose.db.yml
      service: nats

  # AI services (resource intensive - optional)
  ollama:
    extends:
      file: services/ai-services/docker-compose.ai.yml
      service: ollama
    profiles:
      - ai
      - full

  # Voice services (resource intensive - optional)
  whisper-stt:
    extends:
      file: services/voice-services/docker-compose.voice.yml
      service: whisper-stt
    profiles:
      - voice
      - full

  coqui-tts:
    extends:
      file: services/voice-services/docker-compose.voice.yml
      service: coqui-tts
    profiles:
      - voice
      - full

  voice-gateway:
    extends:
      file: services/voice-services/docker-compose.voice.yml
      service: voice-gateway
    profiles:
      - voice
      - full
    depends_on:
      - whisper-stt
      - coqui-tts

volumes:
  postgres_data:
  redis_data:
  nats_data:
  ollama_data:
  whisper_models:
  tts_models:

networks:
  startales:
    driver: bridge
