export interface GMTPersonality {
  id: string
  name: string
  synopsis: string
  tone: 'humorous' | 'inspirational' | 'adventurous' | 'competitive' | 'cozy' | 'noir' | 'grim' | 'diplomatic' | 'mythic' | 'horror'
  styleTokens: string[]
  pacingBeatsPer5Min: number
  recapCadenceMin: number
  quipFrequency: 'low' | 'medium' | 'high'
  safetyEmphasis: 'light' | 'moderate' | 'strong'
  twistProfile: 'surprise' | 'foreshadowed' | 'ironic' | 'fated'
  encounterTilt: Array<'social' | 'exploration' | 'combat' | 'puzzle'>
  imageStyle: string[]
  ttsProfile: { timbre: 'bright' | 'neutral' | 'warm' | 'gravelly'; rate: 'slow' | 'normal' | 'fast' }
}

export const GM_PERSONALITY_PRESETS: GMTPersonality[] = [
  {
    id: 'humorous-pulp',
    name: 'Humorous Pulp',
    synopsis: 'Light, quippy narration with Saturday‑matinee energy and slapstick complications.',
    tone: 'humorous',
    styleTokens: ['pulp', 'quip', 'lighthearted'],
    pacingBeatsPer5Min: 8,
    recapCadenceMin: 6,
    quipFrequency: 'high',
    safetyEmphasis: 'moderate',
    twistProfile: 'surprise',
    encounterTilt: ['exploration', 'social', 'combat'],
    imageStyle: ['bright', 'pulp-ink', 'posterized'],
    ttsProfile: { timbre: 'bright', rate: 'fast' },
  },
  {
    id: 'inspirational-epic',
    name: 'Inspirational Epic',
    synopsis: 'Heroic, aspirational voice with long-arc payoffs and soaring diction.',
    tone: 'inspirational',
    styleTokens: ['epic', 'heroic', 'soaring'],
    pacingBeatsPer5Min: 6,
    recapCadenceMin: 8,
    quipFrequency: 'low',
    safetyEmphasis: 'moderate',
    twistProfile: 'fated',
    encounterTilt: ['exploration', 'combat'],
    imageStyle: ['epic-matte', 'wide-vista'],
    ttsProfile: { timbre: 'warm', rate: 'normal' },
  },
  {
    id: 'adventurous-explorer',
    name: 'Adventurous Explorer',
    synopsis: 'Wonder-forward discovery with descriptive vistas and balanced pacing.',
    tone: 'adventurous',
    styleTokens: ['exploration', 'wonder', 'curiosity'],
    pacingBeatsPer5Min: 7,
    recapCadenceMin: 7,
    quipFrequency: 'medium',
    safetyEmphasis: 'light',
    twistProfile: 'foreshadowed',
    encounterTilt: ['exploration', 'puzzle', 'social'],
    imageStyle: ['cartography', 'travelogue'],
    ttsProfile: { timbre: 'neutral', rate: 'normal' },
  },
  {
    id: 'competitive-sportscaster',
    name: 'Competitive Sportscaster',
    synopsis: 'Energetic play-by-play with score focus and crisp highlights.',
    tone: 'competitive',
    styleTokens: ['sportscast', 'energetic', 'score'],
    pacingBeatsPer5Min: 9,
    recapCadenceMin: 5,
    quipFrequency: 'medium',
    safetyEmphasis: 'light',
    twistProfile: 'surprise',
    encounterTilt: ['combat', 'puzzle', 'social'],
    imageStyle: ['broadcast-graphics'],
    ttsProfile: { timbre: 'bright', rate: 'fast' },
  },
  {
    id: 'cozy-wholesome',
    name: 'Cozy Wholesome',
    synopsis: 'Gentle stakes and community-forward beats with soft cadence.',
    tone: 'cozy',
    styleTokens: ['wholesome', 'gentle', 'repair'],
    pacingBeatsPer5Min: 5,
    recapCadenceMin: 10,
    quipFrequency: 'low',
    safetyEmphasis: 'strong',
    twistProfile: 'foreshadowed',
    encounterTilt: ['social', 'exploration', 'puzzle'],
    imageStyle: ['soft-palette', 'warm-light'],
    ttsProfile: { timbre: 'warm', rate: 'slow' },
  },
  {
    id: 'noir-hardboiled',
    name: 'Hardboiled Noir',
    synopsis: 'Terse metaphors, moral dilemmas, and shadowy intrigue.',
    tone: 'noir',
    styleTokens: ['noir', 'metaphor', 'laconic'],
    pacingBeatsPer5Min: 6,
    recapCadenceMin: 8,
    quipFrequency: 'low',
    safetyEmphasis: 'moderate',
    twistProfile: 'ironic',
    encounterTilt: ['social', 'exploration'],
    imageStyle: ['low-key', 'neon-noir'],
    ttsProfile: { timbre: 'gravelly', rate: 'slow' },
  },
  {
    id: 'grim-survival',
    name: 'Grim Survival',
    synopsis: 'Scarcity and hazard-forward tension with slow recovery.',
    tone: 'grim',
    styleTokens: ['scarcity', 'hazard', 'tension'],
    pacingBeatsPer5Min: 5,
    recapCadenceMin: 9,
    quipFrequency: 'low',
    safetyEmphasis: 'strong',
    twistProfile: 'surprise',
    encounterTilt: ['exploration', 'combat'],
    imageStyle: ['muted', 'bleak'],
    ttsProfile: { timbre: 'neutral', rate: 'slow' },
  },
  {
    id: 'high-diplomacy',
    name: 'High Diplomacy',
    synopsis: 'Politics and intrigue with formal diction and reputation swings.',
    tone: 'diplomatic',
    styleTokens: ['court', 'protocol', 'intrigue'],
    pacingBeatsPer5Min: 6,
    recapCadenceMin: 8,
    quipFrequency: 'low',
    safetyEmphasis: 'moderate',
    twistProfile: 'foreshadowed',
    encounterTilt: ['social', 'puzzle'],
    imageStyle: ['portraiture', 'regalia'],
    ttsProfile: { timbre: 'neutral', rate: 'normal' },
  },
  {
    id: 'mythic-saga',
    name: 'Mythic Saga',
    synopsis: 'Archetypal beats, ritual cadence, and choral grandeur.',
    tone: 'mythic',
    styleTokens: ['mythic', 'ritual', 'prophecy'],
    pacingBeatsPer5Min: 5,
    recapCadenceMin: 10,
    quipFrequency: 'low',
    safetyEmphasis: 'moderate',
    twistProfile: 'fated',
    encounterTilt: ['exploration', 'social', 'combat'],
    imageStyle: ['fresco', 'mural'],
    ttsProfile: { timbre: 'warm', rate: 'slow' },
  },
  {
    id: 'cosmic-horror',
    name: 'Cosmic Horror (consent-gated)',
    synopsis: 'Oblique dread with redaction-friendly narration and strict safety tools.',
    tone: 'horror',
    styleTokens: ['oblique', 'dread', 'veil'],
    pacingBeatsPer5Min: 4,
    recapCadenceMin: 10,
    quipFrequency: 'low',
    safetyEmphasis: 'strong',
    twistProfile: 'ironic',
    encounterTilt: ['exploration', 'puzzle'],
    imageStyle: ['abstracted', 'high-contrast'],
    ttsProfile: { timbre: 'neutral', rate: 'slow' },
  },
]


