version: '3.8'

services:
  api:
    build:
      context: ../../..
      dockerfile: docker/services/api/Dockerfile.demo
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    command: ["node", "comprehensive-demo-server.cjs"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/witter/feed"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - startales

networks:
  startales:
    external: true
