version: '3.8'

services:
  communication-api:
    build:
      context: ../../../
      dockerfile: docker/services/communication/Dockerfile
    ports:
      - "4003:4003"
    environment:
      - NODE_ENV=production
      - PORT=4003
    networks:
      - startales-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4003/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    container_name: startales-communication-api

networks:
  startales-network:
    external: true

