# Ollama Service Configuration
version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: startales-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
      - ./models:/app/models  # Local model storage
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - startales-network

  # Model initialization service
  ollama-init:
    image: ollama/ollama:latest
    container_name: startales-ollama-init
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ollama_models:/root/.ollama
      - ./init-models.sh:/init-models.sh
    environment:
      - OLLAMA_HOST=ollama:11434
    command: ["/bin/bash", "/init-models.sh"]
    networks:
      - startales-network
    restart: "no"

volumes:
  ollama_models:
    driver: local

networks:
  startales-network:
    external: true
