name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci --no-audit --no-fund
      - name: Typecheck
        run: npm run typecheck
      - name: Build packages
        run: npm run build:packages
      - name: Unit tests (workspaces)
        run: npm run test:packages
      - name: API tests (Jest)
        run: npm run test:api
      - name: Upload coverage (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage
            coverage-api

  e2e:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci --no-audit --no-fund
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright e2e
        env:
          DEMO_START: '1'
          PORT: '4011'
        run: npm run e2e
      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report


