apiVersion: apps/v1
kind: Deployment
metadata:
  name: stt
  namespace: startales
  labels:
    app: stt
    component: ai-service
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: stt
  template:
    metadata:
      labels:
        app: stt
        component: ai-service
    spec:
      containers:
      - name: stt
        image: startales/stt:latest
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: startales-config
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 2
        volumeMounts:
        - name: stt-models
          mountPath: /app/models
      volumes:
      - name: stt-models
        persistentVolumeClaim:
          claimName: stt-models-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: stt
  namespace: startales
  labels:
    app: stt
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: stt
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stt-models-pvc
  namespace: startales
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stt-hpa
  namespace: startales
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stt
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
